name: CI

on:
  push:
  pull_request:
    branches:
      - dev
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add/Update submodules
        run: |
          yarn submodules:init
          yarn submodules:update

      - name: Install
        run: yarn install

      # - name: Chromatic
      #   uses: chromaui/action@v1
      #   with:
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Jest
        run: yarn jest

      - name: Build
        run: yarn build

      - name: Cypress
        uses: cypress-io/github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          install: false
          browser: firefox
          start: yarn start
          wait-on-timeout: 120
          wait-on: 'http://localhost:3000'
          spec: src/tests/cypress/integration/**/*spec.ts
